### ISSUE TITLE
Facing id issue on ios

### ISSUE THREAD

**Issue by MuhammadSufyanMalik** [Bytx-youtube/updateavailable#1]
Hi, how to give id for ios?
https://apps.apple.com/us/app/snapchat/id447188370
I tried this but ıt says that not found and null.

Thanks

**Comment by MuhammadSufyanMalik** [comment]
using this you can find easily
https://mrvirk.com/how-to-find-app-bundle-id-ios.html

Thanks

**Comment by Bytx-youtube** [comment]
for flutter, the id for android and ios usually the same
